templates:
    - Carthage/Checkouts/legacy/Sources/Templates
output:
    LegacyDemo/Generated
prune:
    true
verbose:
    true
project:
    file:
        LegacyDemo.xcodeproj
    target:
        name: LegacyDemo
