language: objective-c
osx_image: xcode13.3
branches:
  only:
    - master
script: set -o pipefail && xcodebuild test -project LegacyDemo.xcodeproj -scheme LegacyDemo -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty
